name: Build & test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.302
    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.410
    - name: Install dependencies
      run: | 
        dotnet nuget add source --username nazarovsa --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github_telegram_bot "https://nuget.pkg.github.com/TelegramBots/index.json" 
        dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
