name: Publish nuget packages
on:
  push:
    tags: 
      - '*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.302
    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.102
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack
      env: 
        NUGET_SOURCE: https://api.nuget.org/v3/index.json
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
      run: | 
        dotnet build --no-restore
        ./publish-nuget.sh "$NUGET_SOURCE" "$NUGET_KEY" "${GITHUB_REF##*/}"
